name: estudo_dart
description: Estudando a linguagem Dart.
version: 0.0.1
# repository: https://github.com/AntonioGuilhermeDev/estudo_dart

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
